### ISSUE TITLE
Count the Number of Base Pairs in the DNA (AT & GC)

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#103]

**Comment by akshatjainei** [comment]
Which file to refer? Kindly add some description as well

**Comment by Verisimilitude11** [comment]
In https://github.com/Verisimilitude11/DNAnalyzer/tree/main/src/DNAnalyzer, please count the number of base pairs (# of ATs + # of TAs + # of GCs + # of CGs). Let me know if you have any other questions.

**Comment by Verisimilitude11** [comment]
@akshatjainei are you interested in doing this?

**Comment by garyglatfelter** [comment]
Wouldn't this just be the length of the input string? 

Or is the desired function to provide a count of each type of pair? like so:
example input: 'GATTACA'

GC = 1
AT = 3
TA = 2
CG = 1

**Comment by Verisimilitude11** [comment]
Correct, it would output the count of each type of pair:
GC = 1
AT = 3
TA = 2
CG = 1

**Comment by garyglatfelter** [comment]
understood. yeah that should be pretty easy, I can do that

**Comment by Verisimilitude11** [comment]
Cool, I assigned it to you. Thanks for working on this!

**Comment by garyglatfelter** [comment]
A couple of follow-up questions:

Can I/Should I assume all text will be in ASCII ? Do you have any performance expectations?

What is the largest input fie/string expected? (I ask because it is probably easiest to load the whole file to memory and then process. however, I imagine the files can get very large so memory size may be a concern)

**Comment by garyglatfelter** [comment]
I think I answered some of my previous questions. You had only asked to handle String, and for some reason, I was thinking I'd also be making the function to input files. 

Anyway, I've added two options for counting base pairs. One is a straightforward traversal of char array. The second function I attempted parallel streams. I have an older computer so perhaps I'm not getting the full performance gains of running a parallel stream but, at least for me, the char array is faster (string length of 'dnalong.fa': 100,000,000 characters; Array: ~900 milliseconds; Parallel Stream: ~1200 milliseconds).

Perhaps if you have a more recent CPU and when you have a moment, you can test to see if parallel stream is more performant. Check under the standard output of the test report in "\DNAnalyzer\build\reports\tests\test" after running the tests. If parallel is of no benefit even on more modern cpu, I can remove that function.

**Comment by Verisimilitude11** [comment]
Hey @garyglatfelter, sorry I seem to have somehow missed your previous message. Yes, all the text is in ASCII and the largest input string would be a 4 GB txt file. Sure, I have a 12th gen intel i9 CPU so I can test the parallel stream. I'm really interested in seeing how you implemented it - I'm sure it'll be very useful. Could you please submit a PR so that I can view/test the code? Thanks for contributing! Also, maybe we can implement a parallel stream for some of the other features as well, to improve the performance. Let me know what you think.

**Comment by garyglatfelter** [comment]
Np.
For just counting occurrences like this, it's actually pretty easy. But because it's easy, there may not be enough a performance gain to offset the additional overhead the jvm has to manage for the extra threads. When calculations become more complex, the gains are more favorable. Which might be why the plain old character array is winning out here.

I would like to learn more about parallel streams, multithreading, performance stuff, etc, so if you've got something in mind I can take a look. I don't know much, but it'll give me some practice at the very least.

**Comment by Verisimilitude11** [comment]
Sure. Here are a couple of places in which you could look into implementing parallel streams/multithreading:
- protein/ProteinFinder.java/getProtein and /addProtein
- ReadingFrames.java
- DNAAnalysis.java/protein sequence

Thanks again for your interest in working on this. This will be useful to us, and I'm excited to see what you will implement.
