### ISSUE TITLE
Store .fa DNA files in Smaller File Size

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#215]
Use a more efficient file format as the DNA FASTA files right now are very big and take a lot of time to download while cloning the DNAnalyzer repository.

**Comment by MartinGallauner** [comment]
I would like to look into this, please assign to me :)

**Comment by Verisimilitude11** [comment]
Sure!

**Comment by LimesKey** [comment]
For some more information, I use [7-Zip](https://www.7-zip.org/) as my compression & zip file manager because it's open source, it can compress a 100MB. FA file into 26.5MB using the default LZMA compression method set to "Ultra Compression". Text files can usually be very easily compressed, especially .fasta files.

**Comment by Verisimilitude11** [comment]
Thanks for this @LimesKey. @MartinGallauner could you please compress all of the DNA files that we have under ./assets/dna/* using 7-Zip or a similar tool? Thanks for working on this!

**Comment by MartinGallauner** [comment]
Understood. Will do that no later that tomorrow!

**Comment by Verisimilitude11** [comment]
No worries, thank you so much for contributing!
